function [smallConfusion] = condenseConfusion(largeConfusion)
smallConfusion = [largeConfusion(1,1)... 
                  (largeConfusion(1,2) + largeConfusion(1,3));...
                  (largeConfusion(2,1) + largeConfusion(3,1))...
                  (largeConfusion(2,2) + largeConfusion(2,3) + largeConfusion(3,2)+largeConfusion(3,3))];
end